
// This file has been generated by the GUI designer. Do not modify.
namespace OpenGraal.GraalIM
{
	public partial class RCWindow
	{
		private global::Gtk.Table table2;
		private global::Gtk.Entry entry1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textview1;
		private global::Gtk.Table table3;
		private global::Gtk.Table table4;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image10;
		private global::Gtk.Image image11;
		private global::Gtk.Image image12;
		private global::Gtk.Image image13;
		private global::Gtk.Image image14;
		private global::Gtk.Image image7;
		private global::Gtk.Image image8;
		private global::Gtk.Image image9;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenGraal.GraalIM.RCWindow
			this.Name = "OpenGraal.GraalIM.RCWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("OpenGraal Remote Control 2013/06/03");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rcicon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OpenGraal.GraalIM.RCWindow.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(1)), false);
			this.table2.Name = "table2";
			// Container child table2.Gtk.Table+TableChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.table2.Add (this.entry1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.entry1]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.Editable = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(3));
			this.textview1.PixelsInsideWrap = 7;
			this.GtkScrolledWindow.Add (this.textview1);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table3.WidthRequest = 476;
			this.table3.HeightRequest = 148;
			this.table3.Name = "table3";
			// Container child table3.Gtk.Table+TableChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(7)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(1));
			this.table4.ColumnSpacing = ((uint)(1));
			this.table4.BorderWidth = ((uint)(5));
			// Container child table4.Gtk.Table+TableChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.table4.Add (this.fixed2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.fixed2]));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image10 = new global::Gtk.Image ();
			this.image10.CanDefault = true;
			this.image10.Name = "image10";
			this.image10.Xalign = 0F;
			this.image10.Yalign = 0F;
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_serveroptions_normal.png");
			this.table4.Add (this.image10);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.image10]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(6));
			w5.RightAttach = ((uint)(7));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image11 = new global::Gtk.Image ();
			this.image11.CanDefault = true;
			this.image11.Name = "image11";
			this.image11.Xalign = 0F;
			this.image11.Yalign = 0F;
			this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_accounts_normal.png");
			this.table4.Add (this.image11);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4 [this.image11]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image12 = new global::Gtk.Image ();
			this.image12.CanDefault = true;
			this.image12.Name = "image12";
			this.image12.Xalign = 0F;
			this.image12.Yalign = 0F;
			this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_toalls_normal.png");
			this.table4.Add (this.image12);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4 [this.image12]));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image13 = new global::Gtk.Image ();
			this.image13.CanDefault = true;
			this.image13.Name = "image13";
			this.image13.Xalign = 0F;
			this.image13.Yalign = 0F;
			this.image13.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_serverflags_normal.png");
			this.table4.Add (this.image13);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4 [this.image13]));
			w8.LeftAttach = ((uint)(5));
			w8.RightAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image14 = new global::Gtk.Image ();
			this.image14.CanDefault = true;
			this.image14.Name = "image14";
			this.image14.Xalign = 0F;
			this.image14.Yalign = 0F;
			this.image14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_options_normal.png");
			this.table4.Add (this.image14);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4 [this.image14]));
			w9.LeftAttach = ((uint)(4));
			w9.RightAttach = ((uint)(5));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image7 = new global::Gtk.Image ();
			this.image7.CanDefault = true;
			this.image7.Name = "image7";
			this.image7.Xalign = 0F;
			this.image7.Yalign = 0F;
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_playerlist_normal.png");
			this.table4.Add (this.image7);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4 [this.image7]));
			w10.XOptions = ((global::Gtk.AttachOptions)(0));
			w10.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.image8 = new global::Gtk.Image ();
			this.image8.CanDefault = true;
			this.image8.Name = "image8";
			this.image8.Xalign = 1F;
			this.image8.Yalign = 1F;
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_folderoptions_normal.png");
			this.table4.Add (this.image8);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4 [this.image8]));
			w11.LeftAttach = ((uint)(6));
			w11.RightAttach = ((uint)(7));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.image9 = new global::Gtk.Image ();
			this.image9.CanDefault = true;
			this.image9.Name = "image9";
			this.image9.Xalign = 0F;
			this.image9.Yalign = 0F;
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenGraal.GraalIM.Resources.rc_images.rc_filebrowser_normal.png");
			this.table4.Add (this.image9);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4 [this.image9]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(0));
			w12.YOptions = ((global::Gtk.AttachOptions)(0));
			this.table3.Add (this.table4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.table4]));
			w13.YPadding = ((uint)(11));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table2.Add (this.table3);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.table3]));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 476;
			this.DefaultHeight = 310;
			this.Show ();
			this.ResizeChecked += new global::System.EventHandler (this.OnResize);
			this.image7.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.PlayerlistClicked);
			this.image7.Unmapped += new global::System.EventHandler (this.OnImage7Unmapped);
			this.image7.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.PlayerlistRelease);
		}
	}
}
